- name: 'restart network-manager'
  become: yes
  service:
    name: network
    state: restarted

- name: 'rebuild fonts cache'
  become: yes
  shell: 'fc-cache -v -f'

- name: 'reload sysctl'
  become: yes
  shell: 'sysctl --system'

- name: 'update apt package list'
  become: yes
  apt:
    update_cache: yes
