- name: Create User Fonts directory
  file:
    path: /home/{{ ansible_user_id }}/.local/share/fonts/
    state: directory

# Iosevka
- name: Download Iosevka Default Fonts
  get_url:
    url: https://github.com/be5invis/Iosevka/releases/download/v2.3.0/iosevka-ss09-2.3.0.zip
    dest: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-ss09-2.3.0.zip
- name: Download Iosevka Terminal Fonts
  get_url:
    url: https://github.com/be5invis/Iosevka/releases/download/v2.3.0/iosevka-term-ss09-2.3.0.zip
    dest: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-term-ss09-2.3.0.zip
- name: Create Iosevka Default Fonts directory
  file:
    path: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-ss09-2.3.0/
    state: directory
- name: Create Iosevka Terminal Fonts directory
  file:
    path: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-term-ss09-2.3.0/
    state: directory
- name: Extract Iosevka Default Fonts
  unarchive:
    src: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-ss09-2.3.0.zip
    dest: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-ss09-2.3.0
    creates: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-ss09-2.3.0/tff/iosevka-ss09-bold.ttf
- name: Extract Iosevka Terminal Fonts
  unarchive:
    src: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-term-ss09-2.3.0.zip
    dest: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-term-ss09-2.3.0
    creates: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-term-ss09-2.3.0/tff/iosevka-term-ss09-bold.ttf
- name: Copy Iosevka Default Fonts
  copy:
    src: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-ss09-2.3.0/ttf/
    dest: /home/{{ ansible_user_id }}/.local/share/fonts/
  notify:
    - "rebuild fonts cache"
- name: Copy Iosevka Terminal Fonts
  copy:
    src: /home/{{ ansible_user_id }}/.ansible/downloads/iosevka-term-ss09-2.3.0/ttf/
    dest: /home/{{ ansible_user_id }}/.local/share/fonts/
  notify:
    - "rebuild fonts cache"

# Nerd Fonts DejaVu Sans Mono
- name: Download DejaVu Sans Mono Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.ttf?raw=true
    dest: /home/{{ ansible_user_id }}/.ansible/downloads/deja-vu-sans-mono-nerd-font-complete.tff
- name: Copy DejaVu Sans Mono Font
  copy:
    src: /home/{{ ansible_user_id }}/.ansible/downloads/deja-vu-sans-mono-nerd-font-complete.tff
    dest: /home/{{ ansible_user_id }}/.local/share/fonts/
  notify:
  - "rebuild fonts cache"
