- include: pre.yml
- include: apt-update.yml
- include: ssh.yml

- include: aspell.yml
- include: chromium.yml
- include: core-utils.yml
- include: dev-libs.yml
- include: docker.yml
- include: dropbox.yml
- include: ffmpeg.yml
- include: fonts.yml
- include: gimp.yml
- include: git-rebase-tool.yml
- include: git-repositories.yml
- include: gnome-extensions.yml
- include: imagemagick.yml
- include: jq.yml
- include: keepassxc.yml
- include: nvm.yml
- include: rust.yml
- include: slack.yml
- include: stow.yml
- include: terminator.yml
- include: tilix.yml
- include: wavebox.yml
- include: zsh.yml

- include_tasks: "system/{{ ansible_product_name }}.yml"
  when: ansible_product_name is defined
