- include: pre.yml
- include: apt-update.yml
- include: ssh.yml

- include: aspell.yml
- include: chromium.yml
- include: core-utils.yml
- include: dev-libs.yml
- include: docker.yml
- include: ffmpeg.yml
- include: fonts.yml
- include: geary.yml
- include: gimp.yml
- include: git-rebase-tool.yml
- include: gitk.yml
- include: gnome-applets.yml
- include: gnome-extensions.yml
- include: gource.yml
- include: imagemagick.yml
- include: inkscape.yml
- include: jq.yml
- include: kazam.yml
- include: keepassxc.yml
- include: lsd.yml
- include: flatpak.yml
- include: jetbrains-toolbox.yml
- include: marktext.yml
- include: mozilla.yml
- include: nvm.yml
- include: python.yml
- include: rust.yml
- include: shellcheck.yml
- include: slack.yml
- include: spideroak.yml
- include: stow.yml
# - include: strongswan.yml
- include: sysctl.yml
- include: tilix.yml
- include: virtualbox.yml
- include: wavebox.yml
- include: xournal.yml
- include: yubikey.yml
- include: zsh.yml

- include: git-repositories.yml

- include_tasks: "system/{{ ansible_product_name }}.yml"
  when:
    - ansible_product_name is defined
    - (role_path + '/tasks/system/' + ansible_product_name + '.yml') is is_file

- include_tasks: "host/{{ ansible_hostname }}.yml"
  when:
    - ansible_hostname is defined
    - (role_path + '/tasks/host/' + ansible_hostname + '.yml') is is_file

