- name: Check if Slack is installed
  command: dpkg -S slack-desktop
  register: slack_check_deb
  failed_when: slack_check_deb.rc > 1
  changed_when: slack_check_deb.rc == 1

- name: Install slack
  become: true
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-3.4.2-amd64.deb
  when: slack_check_deb.rc == 1
