- name: Setup SSH Config
  copy:
    src: "files/ssh_config"
    dest: "/home/{{ ansible_user_id }}/.ssh/config"
    mode: 0600
- name: Create SSH configs directory
  file:
    path: "/home/{{ ansible_user_id }}/.ssh/config.d"
    state: directory
- name: Add SSH configs
  template:
    src: "files/ssh_host_config_template"
    dest: "/home/{{ ansible_user_id }}/.ssh/config.d/{{ item.name }}"
  with_items: "{{ ssh_config }}"

- name: Copy private ssh keys for {{ ansible_hostname }}
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user_id }}/.ssh/"
    mode: 0600
  with_fileglob:
    - "/home/{{ ansible_user_id }}/Sync/ssh-keys/{{ ansible_hostname }}-*"
